### ISSUE TITLE
Core's settings provider does not provide an FS adapter (anymore)

### ISSUE THREAD

**Issue by IngwiePhoenix** [os-js/osjs-server#14]
After doing these changes:

```js
// Server (src/server/index.js)
osjs.register(SettingsServiceProvider, {
  args: {
    adapter: 'fs'
  }
});

// Client (src/client/index.js)
osjs.register(SettingsServiceProvider, {
  args: {
    adapter: 'server'
  }
});
```

I get this error:
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at Promise (/home/osjs/OS.js/node_modules/@osjs/server/src/utils/vfs.js:165:49)
    at new Promise (<anonymous>)
    at module.exports.parseFields (/home/osjs/OS.js/node_modules/@osjs/server/src/utils/vfs.js:159:60)
    at /home/osjs/OS.js/node_modules/@osjs/server/src/filesystem.js:106:41
    at Object.request (/home/osjs/OS.js/node_modules/@osjs/server/src/providers/vfs.js:114:55)
    at request (/home/osjs/OS.js/node_modules/@osjs/server/src/settings.js:48:23)
    at read (/home/osjs/OS.js/node_modules/@osjs/server/src/settings.js:79:7)
    at mkdir.then (/home/osjs/OS.js/node_modules/@osjs/server/src/settings.js:95:17)
```

**Comment by andersevenrud** [comment]
Publishing new `@osjs/server` now :)
