### ISSUE TITLE
Add option to write log to file

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-server#17]
The internal logging system could use an option to pipe the contents to a file.

It already streams to stdio, so this could be redirected easily.

**Comment by PriNet** [comment]
syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\PrintHood',
  filename: 'C:\\Users\\User\\PrintHood'
}
Error: EPERM: operation not permitted, watch 'C:\Users\User\Templates'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\Templates',
  filename: 'C:\\Users\\User\\Templates'
}
Error: EPERM: operation not permitted, watch 'C:\Users\User\Start Menu'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\Start Menu',
  filename: 'C:\\Users\\User\\Start Menu'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Application Data'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Application Data',
  filename: 'C:\\Users\\_ashbackuppb_\\Application Data'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Local Settings'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Local Settings',
  filename: 'C:\\Users\\_ashbackuppb_\\Local Settings'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\My Documents'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\My Documents',
  filename: 'C:\\Users\\_ashbackuppb_\\My Documents'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Cookies'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Cookies',
  filename: 'C:\\Users\\_ashbackuppb_\\Cookies'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\NetHood'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\NetHood',
  filename: 'C:\\Users\\_ashbackuppb_\\NetHood'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Recent'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Recent',
  filename: 'C:\\Users\\_ashbackuppb_\\Recent'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Start Menu'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Start Menu',
  filename: 'C:\\Users\\_ashbackuppb_\\Start Menu'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Templates'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Templates',
  filename: 'C:\\Users\\_ashbackuppb_\\Templates'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\SendTo'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\SendTo',
  filename: 'C:\\Users\\_ashbackuppb_\\SendTo'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\PrintHood'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\PrintHood',
  filename: 'C:\\Users\\_ashbackuppb_\\PrintHood'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Public\Documents\My Videos'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Public\\Documents\\My Videos',
  filename: 'C:\\Users\\Public\\Documents\\My Videos'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Public\Documents\My Pictures'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Public\\Documents\\My Pictures',
  filename: 'C:\\Users\\Public\\Documents\\My Pictures'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Public\Documents\My Music'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Public\\Documents\\My Music',
  filename: 'C:\\Users\\Public\\Documents\\My Music'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Default\Documents\My Music'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Default\\Documents\\My Music',
  filename: 'C:\\Users\\Default\\Documents\\My Music'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Default\Documents\My Pictures'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Default\\Documents\\My Pictures',
  filename: 'C:\\Users\\Default\\Documents\\My Pictures'
}
Error: EPERM: operation not permitted, watch 'C:\Users\Default\Documents\My Videos'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\Default\\Documents\\My Videos',
  filename: 'C:\\Users\\Default\\Documents\\My Videos'
}
Error: EPERM: operation not permitted, watch 'C:\Users\User\Documents\My Music'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\Documents\\My Music',
  filename: 'C:\\Users\\User\\Documents\\My Music'
}
Error: EPERM: operation not permitted, watch 'C:\Users\User\Documents\My Pictures'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\Documents\\My Pictures',
  filename: 'C:\\Users\\User\\Documents\\My Pictures'
}
Error: EPERM: operation not permitted, watch 'C:\Users\User\Documents\My Videos'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\User\\Documents\\My Videos',
  filename: 'C:\\Users\\User\\Documents\\My Videos'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Documents\My Music'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Documents\\My Music',
  filename: 'C:\\Users\\_ashbackuppb_\\Documents\\My Music'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Documents\My Picture
s'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Documents\\My Pictures',
  filename: 'C:\\Users\\_ashbackuppb_\\Documents\\My Pictures'
}
Error: EPERM: operation not permitted, watch 'C:\Users\_ashbackuppb_\Documents\My Videos'

    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at createFsWatchInstance (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:38:15)

    at setFsWatchListener (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\OS.js\node_modules\chokidar\lib\nodef
s-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\OS.js\node_modules\chokidar\lib\nodefs-hand
ler.js:429:19)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:477:19
)
    at FSWatcher.<anonymous> (C:\OS.js\node_modules\chokidar\lib\nodefs-handler.js:482:16
)
    at FSReqCallback.oncomplete (fs.js:166:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\_ashbackuppb_\\Documents\\My Videos',
  filename: 'C:\\Users\\_ashbackuppb_\\Documents\\My Videos'
}

**Comment by PriNet** [comment]
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (C:\OS.js\node_modules\express\lib\response.js:425:11)
    at C:\OS.js\node_modules\@osjs\server\src\providers\core.js:141:36
    at Layer.handle [as handle_request] (C:\OS.js\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\OS.js\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\OS.js\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\OS.js\node_modules\express\lib\router\layer.js:95:5)
    at C:\OS.js\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\OS.js\node_modules\express\lib\router\index.js:335:12)
    at next (C:\OS.js\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\OS.js\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\OS.js\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\OS.js\node_modules\express\lib\router\index.js:317:13)
    at C:\OS.js\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\OS.js\node_modules\express\lib\router\index.js:335:12)
    at next (C:\OS.js\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\OS.js\node_modules\body-parser\lib\types\urlencoded.js:91:7)

**Comment by andersevenrud** [comment]
Closing this issue, because I feel that running the process behind a manager solves this issue better.
